# Generated by Django 5.2.7 on 2025-10-21 18:36

import django.core.validators
import django.db.models.deletion
import utils.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=80, unique=True, verbose_name='Slug')),
                ('user', models.UUIDField(verbose_name='User')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, validators=[utils.validators.not_only_whitespace], verbose_name='Shop name')),
                ('about', models.TextField(blank=True, max_length=1000, null=True, validators=[utils.validators.not_only_whitespace], verbose_name='About shop')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='shop_profiles', verbose_name='Shop profile photo')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Shop verified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Shop activity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Shop created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Shop updated at')),
            ],
            options={
                'verbose_name_plural': 'Shops',
            },
        ),
        migrations.CreateModel(
            name='ShopBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=100, validators=[utils.validators.not_only_whitespace], verbose_name='Shop branch name')),
                ('about', models.TextField(blank=True, max_length=2000, null=True, verbose_name='About shop branch')),
                ('phone_number', models.CharField(blank=True, null=True, verbose_name='Shop branch phone number')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop', verbose_name='Shop')),
            ],
            options={
                'verbose_name_plural': 'ShopBranches',
            },
        ),
        migrations.CreateModel(
            name='ShopComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.UUIDField(verbose_name='User')),
                ('text', models.TextField(blank=True, max_length=200, null=True, validators=[utils.validators.not_only_whitespace], verbose_name='Comment text')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Comment rating(1-5)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Comment created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Comment updated at')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.shop', verbose_name='Shop')),
            ],
            options={
                'verbose_name_plural': 'ShopComments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ShopMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop_media', verbose_name='Images of shop')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text for image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Shop created at')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop', verbose_name='Shop')),
            ],
            options={
                'verbose_name_plural': 'ShopMedias',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ShopSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_name', models.CharField(max_length=50, verbose_name='Media name')),
                ('media_url', models.URLField(verbose_name='Media url')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
            options={
                'verbose_name_plural': 'ShopSocialMedias',
            },
        ),
    ]
