# Generated by Django 5.2.6 on 2025-10-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsproduct',
            name='product_variation',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='analyticsproduct',
            name='shop',
            field=models.UUIDField(),
        ),
    ]
