# Generated by Django 5.2.7 on 2025-10-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_shop_owner',
            field=models.BooleanField(default=False),
        ),
    ]
